language: go
before_install:
  - apt-get update -qq
  - apt-get install -qq libzmq3-dev
install:
  - go get github.com/jessevdk/go-flags
  - go get github.com/ActiveState/tail
  - go get github.com/howeyc/fsnotify
  - go get -tags zmq_3_x github.com/alecthomas/gozmq
